### ISSUE TITLE
Get camera permissions ahead of time

### ISSUE THREAD

**Issue by floogulinc** [mn-pollinators/buzz-about#131]
We should ask students for camera permissions ahead of using AR to streamline the flow. I think a good point would be to ask for it upon entering the session if its not already granted. We may want to add a custom dialog for this to explain and also properly handle the case where it is denied. 

This comes from @kklamberty's suggestion in https://github.com/mn-pollinators/buzz-about/pull/130#pullrequestreview-467799971.

**Comment by helloworld12321** [comment]
Given that

1. There's a lot of cross-browser variation in this issue, so
2. Solving this might introduce more complexity/flakiness than we have right now, and
3. I think we're at least somewhat satisfied with where this is right now,

I'm going to close this issue as `wontfix`.

(Should we ever want to consider this issue again, we can always open it back up. 🙂)
