### ISSUE TITLE
Debounce interactions on the student view.

### ISSUE THREAD

**Issue by helloworld12321** [mn-pollinators/buzz-about#152]
So that you can't just visit a flower and click the interact button 3 times in a row.

In particular, we could make it so that a student can't go back to the same flower until they've dropped off their pollen in the nest, or we could just set a fixed cooldown so that the student can't visit the same flower twice within some window of time. Up to you! :slightly_smiling_face:

**Comment by floogulinc** [comment]
We have discussed and the current idea is to disable the interact button if the student has interacted with the flower already without going back to the nest.
