### ISSUE TITLE
Make the pollen indicators not selectable text

### ISSUE THREAD

**Issue by helloworld12321** [mn-pollinators/buzz-about#158]
Right now, they're Angular material icons that say things like "lens" or "panorama_fish_eye", which causes some weird behavior. (Namely, if you copy and paste them, it says `panorama_fish_eye panorama_fish_eye panorama_fish_eye` :upside_down_face:)

:mountain: :fish: :eye: :mountain: :fish: :eye: :mountain: :fish: :eye:

**Comment by floogulinc** [comment]
Looks like we would want to use the css [`user-select` property](https://www.w3schools.com/cssref/css3_pr_user-select.asp). We probably want to do this for any text on the AR screen.

**Comment by helloworld12321** [comment]
Sweet, nice find!

**Comment by helloworld12321** [comment]
Fixed in #221.
