### ISSUE TITLE
Freeze when leaving AR on Android

### ISSUE THREAD

**Issue by floogulinc** [mn-pollinators/buzz-about#247]
In my testing on my Pixel 4a on Android 11, many times when AR ends from either the teacher pausing or stopping the session, it completely freezes and doesn't recover until the app is closed.

**Comment by helloworld12321** [comment]
It _seems_ as if this bug was fixed upstream—we can reproduce it on Chrome 89 on Android, but not Chrome 90. (But we'll keep an eye out, just in case it reappears.)

**Comment by helloworld12321** [comment]
(And note that Chrome on Android is auto-updated, so we don't need to be as concerned with supporting older versions.)
