### ISSUE TITLE
In Safari, images in the field guide dialog don't always display

### ISSUE THREAD

**Issue by helloworld12321** [mn-pollinators/buzz-about#257]
It looks like the layout engine sometimes gives them zero height. 🤷🏻‍♂️

<img width="1188" alt="Screen Shot 2021-04-09 at 12 03 06 PM" src="https://user-images.githubusercontent.com/56209343/114216858-16cc5500-992d-11eb-8f0e-673e30195893.png">

Thanks to @kklamberty for bringing this to light!

**Comment by floogulinc** [comment]
I wonder if it's actually failing to download them, can you check the network tab when this happens?

**Comment by helloworld12321** [comment]
Ooh, good suggestion!

Yes, they're here all right—it looks like they're just not getting the right layout.

<img width="1230" alt="Screen Shot 2021-04-09 at 1 21 02 PM" src="https://user-images.githubusercontent.com/56209343/114224239-6fecb680-9936-11eb-8942-45c2767196ac.png">

**Comment by helloworld12321** [comment]
(cross-post from Slack)

Okay, update:

1:
The problem is that, for some reason or another, when Safari calculates the layout, it intermittently fails to give the image the correct size at first.
(In particular, it gives the image zero width.)
Later, when Safari has to re-calculate the layout—say, on window resize—it sizes the image correctly.

2:
We can ameliorate this issue by providing the image with a min-width and min-height, as @kklamberty suggested.
In that case, when Safari botches the layout, the image will take the provided min-width and min-height, rather than 0 width and 0 height.
This patch works better if we know the image dimensions ahead of time—say, if we're using the 512-by-512 square image. That way, we can choose an appropriate min-width and min-height.

**Comment by helloworld12321** [comment]
Here's the current behavior:

https://user-images.githubusercontent.com/56209343/114224519-c954e580-9936-11eb-848f-98eb94689a98.mov

**Comment by helloworld12321** [comment]
And here's the patched behavior (using a 512-square header image with `min-width: 100`  and `min-height: 100`)

https://user-images.githubusercontent.com/56209343/114224728-120c9e80-9937-11eb-85e8-b776b13117b7.mov


(Slightly nicer even if we use a `min-width: 128`)

https://user-images.githubusercontent.com/56209343/114224741-1638bc00-9937-11eb-8671-74ca00391403.mov

**Comment by helloworld12321** [comment]
It's not a perfect fix, but given that this isn't our bug, I feel like we could do worse ¯\_(ツ)_/¯

And the layout is still okay on small screens, FWIW :)


<img width="692" alt="Screen Shot 2021-04-09 at 1 17 58 PM" src="https://user-images.githubusercontent.com/56209343/114224804-2b154f80-9937-11eb-9419-58717f923945.png">
<img width="692" alt="Screen Shot 2021-04-09 at 1 18 03 PM" src="https://user-images.githubusercontent.com/56209343/114224807-2bade600-9937-11eb-8f3a-613519418d92.png">
