### ISSUE TITLE
Refactor the clock logic out of the timer-bar

### ISSUE THREAD

**Issue by helloworld12321** [mn-pollinators/buzz-about#26]
Right now the timer-bar is actually running the clock itself. It should really only be in charge of displaying the time—the actual clock logic should be in a separate service or something like that.

**Comment by helloworld12321** [comment]
As a part of this, `LargeDisplayComponent` shouldn't poll the timer :)

**Comment by floogulinc** [comment]
I wonder if month should actually be an enum.
