### ISSUE TITLE
TSLint in GitHub Actions

### ISSUE THREAD

**Issue by floogulinc** [mn-pollinators/buzz-about#97]
I was wondering if we should add running `ng lint` to our GitHub Actions workflow so we can start checking that. I noticed that not everyone has the TSLint VS Code extension and even then that doesn't guarantee compliance. We may also want to look at something like this: https://github.com/mooyoul/tslint-actions, which adds annotations to the PR for each TSLint issue.

**Comment by helloworld12321** [comment]
I feel like we could go two ways with this:

1. Don't care too much about whether tslint is happy (which is where we're at right now)
2. Care about whether tslint is happy (in which case tying it to our CI is probably necessary)

I kinda like option No. 2! If we take that route, then we don't have to bother with style fixes during code review. Leaving code style to the robots makes formatting disputes much less subjective and helps keep reviews nice and quick :slightly_smiling_face: 

[These people](https://medium.com/palantir/code-review-best-practices-19e02780015f) put it pretty well:

> Expensive human review time should be spent on the program logic rather than style, syntax, or formatting debates. We prefer settling those with automated tooling like Checkstyle, TSLint, Baseline, Prettier, etc.
