### ISSUE TITLE
Refine interact UI in student AR view

### ISSUE THREAD

**Issue by floogulinc** [mn-pollinators/buzz-about#99]
From our showcase discussion:
> The button is disabled if the flower is not blooming. When the button is disabled, it is not very visible. You also, then, are not able to see the name of the flower (since it’s only on the button).

- We might want to display the flower/nest name differently than on the interact button
- The button and other elements need to scale better for displays like iPads
- Debounce interactions so you can't just spam the button
- Provide ~~better~~ feedback that an interaction was registered

**Comment by helloworld12321** [comment]
(I'm going to close this one, since we've split it into several more specific issues :slightly_smiling_face:)
